import java.util.ArrayList;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cliente
 */
public class tgeral extends javax.swing.JFrame {
    ArrayList<Tecnico> infoTec=new ArrayList();
    ArrayList<Aluno> infoAluno=new ArrayList();
    ArrayList<Funcionario> infoFunci=new ArrayList();
    ArrayList<Professor> infoPro=new ArrayList();
    ArrayList<Curso> infoCurso = new ArrayList();
    ArrayList<Diciplinas> infoDic = new ArrayList();

    /**
     * Creates new form principal
     */
    public tgeral() {
        initComponents();
    }

    public tgeral(ArrayList<Aluno> infAlun, ArrayList<Tecnico> infTecn, 
    ArrayList<Funcionario> infFunc, ArrayList<Professor> infProf,
    ArrayList<Curso> infCursop,ArrayList<Diciplinas> infDici) {
        initComponents();
        infoAluno=infAlun;
        infoTec=infTecn;
        infoFunci=infFunc;
        infoPro=infProf;
        infoCurso=infCursop;
        infoDic=infDici;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        aluno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        funcio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        curso = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        dici = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        listaAlun = new javax.swing.JButton();
        listaFunc = new javax.swing.JButton();
        listaCurs = new javax.swing.JButton();
        entraDici = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tecnico = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        professor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fazer registro de alunos");

        aluno.setText("Registrar");
        aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoActionPerformed(evt);
            }
        });

        jLabel2.setText("Fazer registro de funcionários");

        funcio.setText("Registrar");
        funcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcioActionPerformed(evt);
            }
        });

        jLabel3.setText("Fazer registrar de curso");

        curso.setText("Registrar");
        curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoActionPerformed(evt);
            }
        });

        jLabel4.setText("Fazer registro de diciplina");

        dici.setText("Registrar");
        dici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diciActionPerformed(evt);
            }
        });

        jLabel5.setText("Mostra lista de alunos");

        jLabel6.setText("mostra lista de funcionario");

        jLabel7.setText("mostra lista de cursos");

        jLabel8.setText("mostra lista de diciplinas");

        listaAlun.setText("Consultar");
        listaAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAlunActionPerformed(evt);
            }
        });

        listaFunc.setText("Consultar");
        listaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaFuncActionPerformed(evt);
            }
        });

        listaCurs.setText("Consultar");
        listaCurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaCursActionPerformed(evt);
            }
        });

        entraDici.setText("Consultar");
        entraDici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entraDiciActionPerformed(evt);
            }
        });

        jLabel9.setText("mostra lista de tecnicos ");

        tecnico.setText("Consultar");
        tecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecnicoActionPerformed(evt);
            }
        });

        jLabel10.setText("mostra lista de professores ");

        professor.setText("Consultar");
        professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(funcio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(curso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listaAlun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listaFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listaCurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entraDici, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(tecnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(professor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(aluno))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(funcio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(curso))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dici))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(listaAlun))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(listaFunc))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(listaCurs))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(entraDici))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tecnico))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(professor))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoActionPerformed
        // TODO add your handling code here:
        cadastroAluno alu=new cadastroAluno(infoAluno,infoTec,infoFunci,infoPro,infoCurso,infoDic);
        alu.setLocationRelativeTo(null);
        alu.setVisible(true); 
        dispose();
    }//GEN-LAST:event_alunoActionPerformed

    private void funcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcioActionPerformed
        // TODO add your handling code here:
        cadastro cada=new cadastro(infoAluno,infoTec,infoFunci,infoPro,infoCurso,infoDic);
        cada.setLocationRelativeTo(null);
        cada.setVisible(true); 
        dispose();
    }//GEN-LAST:event_funcioActionPerformed

    private void cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoActionPerformed
        // TODO add your handling code here:
        cadastroCurso cursos=new cadastroCurso(infoAluno,infoTec,infoFunci,infoPro,infoCurso,infoDic);
        cursos.setLocationRelativeTo(null);
        cursos.setVisible(true); 
        dispose();
    }//GEN-LAST:event_cursoActionPerformed

    private void listaAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAlunActionPerformed
        // TODO add your handling code here:
        if(infoAluno.size()>0){
        mostra no=new mostra(infoAluno,infoTec,infoFunci,infoPro,infoCurso,1,infoDic);
        no.setLocationRelativeTo(null);
        no.setVisible(true); 
        dispose();
        }else{
            JOptionPane.showMessageDialog(null, "registros inexistentes");
        }
    }//GEN-LAST:event_listaAlunActionPerformed

    private void listaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaFuncActionPerformed
        // TODO add your handling code here:
        if(infoFunci.size()>0){
        mostra no=new mostra(infoAluno,infoTec,infoFunci,infoPro,infoCurso,3,infoDic);
        no.setLocationRelativeTo(null);
        no.setVisible(true); 
        dispose();
        }else{
            JOptionPane.showMessageDialog(null, "registros inexistentes");
        }
    }//GEN-LAST:event_listaFuncActionPerformed

    private void listaCursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaCursActionPerformed
        // TODO add your handling code here:
        if(infoCurso.size()>0){
        mostra no=new mostra(infoAluno,infoTec,infoFunci,infoPro,infoCurso,5,infoDic);
        no.setLocationRelativeTo(null);
        no.setVisible(true); 
        dispose();
        }else{
            JOptionPane.showMessageDialog(null, "registros inexistentes");
        }
    }//GEN-LAST:event_listaCursActionPerformed

    private void entraDiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entraDiciActionPerformed
        // TODO add your handling code here:
        if(infoDic.size()>0){
        mostra no=new mostra(infoAluno,infoTec,infoFunci,infoPro,infoCurso,6,infoDic);
        no.setLocationRelativeTo(null);
        no.setVisible(true); 
        dispose();
        }else{
            JOptionPane.showMessageDialog(null, "registros inexistentes");
        }
    }//GEN-LAST:event_entraDiciActionPerformed

    private void tecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecnicoActionPerformed
        // TODO add your handling code here:
        if(infoTec.size()>0){
        mostra no=new mostra(infoAluno,infoTec,infoFunci,infoPro,infoCurso,2,infoDic);
        no.setLocationRelativeTo(null);
        no.setVisible(true); 
        dispose();
        }else{
            JOptionPane.showMessageDialog(null, "registros inexistentes");
        }
    }//GEN-LAST:event_tecnicoActionPerformed

    private void professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorActionPerformed
        // TODO add your handling code here:
        if(infoPro.size()>0){
        mostra no=new mostra(infoAluno,infoTec,infoFunci,infoPro,infoCurso,4,infoDic);
        no.setLocationRelativeTo(null);
        no.setVisible(true); 
        dispose();
        }else{
            JOptionPane.showMessageDialog(null, "registros inexistentes");
        }
    }//GEN-LAST:event_professorActionPerformed

    private void diciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diciActionPerformed
        // TODO add your handling code here:
        cadastroDiciplina no=new cadastroDiciplina(infoAluno,infoTec,infoFunci,infoPro,infoCurso,infoDic);
        no.setLocationRelativeTo(null);
        no.setVisible(true); 
        dispose();
    }//GEN-LAST:event_diciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tgeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tgeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tgeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tgeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new tgeral().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aluno;
    private javax.swing.JButton curso;
    private javax.swing.JButton dici;
    private javax.swing.JButton entraDici;
    private javax.swing.JButton funcio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton listaAlun;
    private javax.swing.JButton listaCurs;
    private javax.swing.JButton listaFunc;
    private javax.swing.JButton professor;
    private javax.swing.JButton tecnico;
    // End of variables declaration//GEN-END:variables
}
